### ISSUE TITLE
Feature Request: Flag to Only Update Files With Comment Block

### ISSUE THREAD

**Issue by reggi** [thlorenz/doctoc#80] opened 2015-08-11 01:00 UTC
Is there a flag / option to only add a TOC if there's a comment block?

**Comment by reggi** [comment] 2015-08-11 01:01
I suppose placing a block at the bottom of the file is the only way to ensure it won't get generated when you assign a dir of files.

**Comment by jez** [comment] 2015-08-12 16:52
I actually have a PR out (#68) that would let you do this with a bit of ack/ag magic. @thlorenz just needs to merge and push an npm update.

**Comment by reggi** [comment] 2015-08-12 17:15
Does your pr do `<-- doc toc skip --> ` not sure if thats ideal. I think I'd rather not write comments for each doc. I'd like to see an explicit flag.

```
doctoc **/md.js --explicit
```

And only docs that have the 

```
<!-- START doctoc -->
<!-- END doctoc -->
```

or 

```
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->

<!-- END doctoc generated TOC please keep comment here to allow auto update -->
```

will be written to.

**Comment by jez** [comment] 2015-08-12 18:37
So my PR actually just lets you pass in a list of files to run doctoc on. If you want to exclude specific files, you can add 'DOCTOC SKIP' in comments to the files to exclude and run

```
doctoc $(ack -L 'DOCTOC SKIP')
```

but if you want something like `--explicit`, you can use `-l` (n.b.: lowercase)

```
doctoc $(ack -l 'START doctoc')
```

Of course, you can feel free to use any other program instead of `ack` that lets you search for files and list their names (`ag`, `pt`, `grep`) but `ack` is what I know so you'll have to consult the docs for the other programs.

**Comment by jez** [comment] 2015-08-12 18:38
Closing as duplicate of #66

**Closed** 2015-08-12 18:38 UTC
Labels: duplicate

**Comment by reggi** [comment] 2015-08-13 16:34
@jez you just blew my mind, can't wait to give this a try.

**Comment by keverw** [comment] 2017-03-13 02:47
I'm running `ack -L 'DOCTOC SKIP' | xargs doctoc` like the readme mentions. It's not updating at all.

```shell
ack -L 'DOCTOC SKIP' | xargs doctoc
```

then I get back:

```shel
Unknown option(s): -
Usage: doctoc [mode] [--entryprefix prefix] [--notitle | --title title] [--maxlevel level] <path> (where path is some path to a directory (e.g., .) or a file (e.g., README.md))

Available modes are:
  --bitbucket	bitbucket.org
  --nodejs	nodejs.org
  --github	github.com
  --gitlab	gitlab.com
  --ghost	ghost.org
Defaults to 'github.com'.

```

So it seems like the `-L` that is passed to ack is also being passed to doctoc, and it's erroring out thinking the `-L` was meant for itself maybe?

**Comment by jez** [comment] 2017-03-13 02:53
Could you give the output of just

```
ack -L 'DOCTOC SKIP'
```

?

**Comment by keverw** [comment] 2017-03-13 02:55
```shell
Company Wiki/Certificate-Generator.md
Company Wiki/cheatsheets/typescript.md
Company Wiki/Code-Guidelines - add to .md
Company Wiki/Code-Guidelines.md
Company Wiki/example-files/openssl.cnf
Company Wiki/Git-Guidelines.md
Company Wiki/official-domains-and-accounts.md
Company Wiki/products.md
Company Wiki/README - add to.md
Company Wiki/Set-Up-Dev-Environment.md
```

**Comment by jez** [comment] 2017-03-13 02:57
Since your filenames have spaces in them, it's causing 'xargs' to mess up.

Perhaps try this:

```
ack --print0 -L 'DOCTOC SKIP' | xargs -0 doctoc
```

**Comment by keverw** [comment] 2017-03-13 02:59
Returned an error. Good to know though. I guess the easiest path would just get rid of spaces and use dashes

```shell
ack --print0 -L 'DOCTOC SKIP' | xargs -0 doctoc
fs.js:907
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'Company\ Wiki/Certificate-Generator.md'
    at Object.fs.statSync (fs.js:907:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/doctoc/doctoc.js:103:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

**Comment by jez** [comment] 2017-03-13 02:59
(As a general principle, I try to avoid spaces in filenames whenever they're not necessary, as things tend to break less frequently.)

**Comment by jez** [comment] 2017-03-13 03:01
Looks like you've found a bug in doctoc, relating to spaces in filenames. Feel free to open a separate issue.

**Comment by keverw** [comment] 2017-03-13 03:03
Okay, will do. I'll most likely just get rid of spaces and use dashes. Thank you though for the pointers. First time ever using `xargs`

**Comment by karfau** [comment] 2017-06-24 15:17
As @reggi mentioned earlier there is a difference between *skipping files that have something in them* and *only updating files that contain something* (`START doctoc` and `END doctoc` in this case). It is the difference about implicit vs. explicit effects.

Stating that you can use an additional (shell) tool for that other task of filtering the file, is not considering that most of the options are not as OS independent as doctoc is, meaning I need to prepare different command line script files or `npm run` scripts for each OS to support, just to not affect files that somebody might add.

So I don't agree with this being a duplicate to the skip option.

The question (to @jez or @thlorenz is, if I would invest time to provide a PR for this flag, does this have some chance of being added? 
(I don't care so much about the name, I like `explicit` but `update-only` or something on that lines might be more easy to understand.)

Best Chrisian

**Comment by inventhouse** [comment] 2020-04-30 20:40
Here's a quick one-liner I wrote to do this:

`grep -rl --include '*.md' "START doctoc generated TOC" . | xargs doctoc`
